name: PR check workflow

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Echo hello world
        run: |
          echo "Hello world"
      - name: Install some thing
        run: | 
          apt-get install npm
   

        
