name: PR check workflow

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Echo hello world
        run: |
          echo "Hello world"
      - uses: actions/checkout@v2
   

        
